
import { ROLE, User } from "./types"

export const users: User[] = [
    { id: "1", name: "Alice Johnson", email: "alice.johnson@example.com", username: "AJohnson", role: ROLE.USER, instances: ["1"], nInstances: 1 },
    { id: "1", name: "Alice Johnson", email: "alice.johnson@example.com", username: "AJohnson", role: ROLE.USER, instances: ["1"], nInstances: 1 },
    { id: "1", name: "Alice Johnson", email: "alice.johnson@example.com", username: "AJohnson", role: ROLE.USER, instances: ["1"], nInstances: 1 },
    { id: "1", name: "Alice Johnson", email: "alice.johnson@example.com", username: "AJohnson", role: ROLE.USER, instances: ["1"], nInstances: 1 },
    { id: "1", name: "Alice Johnson", email: "alice.johnson@example.com", username: "AJohnson", role: ROLE.USER, instances: ["1"], nInstances: 1 },
    { id: "1", name: "Alice Johnson", email: "alice.johnson@example.com", username: "AJohnson", role: ROLE.USER, instances: ["1"], nInstances: 1 },
    { id: "1", name: "Bob Smith", email: "bob.smith@example.com", username: "BSmith", role: ROLE.USER, instances: ["1"], nInstances: 1 },
    { id: "1", name: "Carol White", email: "carol.white@example.com", username: "CWhite", role: ROLE.USER, instances: ["1"], nInstances: 1 },
    { id: "1", name: "David Brown", email: "david.brown@example.com", username: "DBrown", role: ROLE.USER, instances: ["1"], nInstances: 1 },
    { id: "1", name: "Eve Davis", email: "eve.davis@example.com", username: "EDavis", role: ROLE.USER, instances: ["1"], nInstances: 1 },
    { id: "1", name: "Frank Wilson", email: "frank.wilson@example.com", username: "FWilson", role: ROLE.USER, instances: ["1"], nInstances: 1 },
    { id: "1", name: "Grace Miller", email: "grace.miller@example.com", username: "GMiller", role: ROLE.USER, instances: ["1"], nInstances: 1 },
    { id: "1", name: "Hank Taylor", email: "hank.taylor@example.com", username: "HTaylor", role: ROLE.USER, instances: ["1"], nInstances: 1 },
    { id: "1", name: "Ivy Anderson", email: "ivy.anderson@example.com", username: "IAnderson", role: ROLE.USER, instances: ["1"], nInstances: 1 },
    { id: "1", name: "Jack Thomas", email: "jack.thomas@example.com", username: "JThomas", role: ROLE.USER, instances: ["1"], nInstances: 1 },
    { id: "1", name: "Kimberly Moore", email: "kimberly.moore@example.com", username: "KMoore", role: ROLE.USER, instances: ["1"], nInstances: 1 },
    { id: "1", name: "Larry Jackson", email: "larry.jackson@example.com", username: "LJackson", role: ROLE.USER, instances: ["1"], nInstances: 1 },
    { id: "1", name: "Mia Martin", email: "mia.martin@example.com", username: "MMartin", role: ROLE.USER, instances: ["1"], nInstances: 1 },
    { id: "1", name: "Nathan Lee", email: "nathan.lee@example.com", username: "NLee", role: ROLE.USER, instances: ["1"], nInstances: 1 },
    { id: "1", name: "Olivia Harris", email: "olivia.harris@example.com", username: "OHarris", role: ROLE.USER, instances: ["1"], nInstances: 1 },
    { id: "1", name: "Paul Clark", email: "paul.clark@example.com", username: "PClark", role: ROLE.USER, instances: ["1"], nInstances: 1 },
    { id: "1", name: "Quinn Lewis", email: "quinn.lewis@example.com", username: "QLewis", role: ROLE.USER, instances: ["1"], nInstances: 1 },
    { id: "1", name: "Rachel Walker", email: "rachel.walker@example.com", username: "RWalker", role: ROLE.USER, instances: ["1"], nInstances: 1 },
    { id: "1", name: "Steve Hall", email: "steve.hall@example.com", username: "SHall", role: ROLE.USER, instances: ["1"], nInstances: 1 },
    { id: "1", name: "Tina Allen", email: "tina.allen@example.com", username: "TAllen", role: ROLE.USER, instances: ["1"], nInstances: 1 },
    { id: "1", name: "Alice Johnson", email: "alice.johnson@example.com", username: "AJohnson", role: ROLE.USER, instances: ["1"], nInstances: 1 },
    { id: "1", name: "Alice Johnson", email: "alice.johnson@example.com", username: "AJohnson", role: ROLE.USER, instances: ["1"], nInstances: 1 },
    { id: "1", name: "Alice Johnson", email: "alice.johnson@example.com", username: "AJohnson", role: ROLE.USER, instances: ["1"], nInstances: 1 },
    { id: "1", name: "Alice Johnson", email: "alice.johnson@example.com", username: "AJohnson", role: ROLE.USER, instances: ["1"], nInstances: 1 },
    { id: "1", name: "Alice Johnson", email: "alice.johnson@example.com", username: "AJohnson", role: ROLE.USER, instances: ["1"], nInstances: 1 },
    { id: "1", name: "Alice Johnson", email: "alice.johnson@example.com", username: "AJohnson", role: ROLE.USER, instances: ["1"], nInstances: 1 },
    { id: "1", name: "Bob Smith", email: "bob.smith@example.com", username: "BSmith", role: ROLE.USER, instances: ["1"], nInstances: 1 },
    { id: "1", name: "Carol White", email: "carol.white@example.com", username: "CWhite", role: ROLE.USER, instances: ["1"], nInstances: 1 },
    { id: "1", name: "David Brown", email: "david.brown@example.com", username: "DBrown", role: ROLE.USER, instances: ["1"], nInstances: 1 },
    { id: "1", name: "Eve Davis", email: "eve.davis@example.com", username: "EDavis", role: ROLE.USER, instances: ["1"], nInstances: 1 },
    { id: "1", name: "Frank Wilson", email: "frank.wilson@example.com", username: "FWilson", role: ROLE.USER, instances: ["1"], nInstances: 1 },
    { id: "1", name: "Grace Miller", email: "grace.miller@example.com", username: "GMiller", role: ROLE.USER, instances: ["1"], nInstances: 1 },
    { id: "1", name: "Hank Taylor", email: "hank.taylor@example.com", username: "HTaylor", role: ROLE.USER, instances: ["1"], nInstances: 1 },
    { id: "1", name: "Ivy Anderson", email: "ivy.anderson@example.com", username: "IAnderson", role: ROLE.USER, instances: ["1"], nInstances: 1 },
    { id: "1", name: "Jack Thomas", email: "jack.thomas@example.com", username: "JThomas", role: ROLE.USER, instances: ["1"], nInstances: 1 },
    { id: "1", name: "Kimberly Moore", email: "kimberly.moore@example.com", username: "KMoore", role: ROLE.USER, instances: ["1"], nInstances: 1 },
    { id: "1", name: "Larry Jackson", email: "larry.jackson@example.com", username: "LJackson", role: ROLE.USER, instances: ["1"], nInstances: 1 },
    { id: "1", name: "Mia Martin", email: "mia.martin@example.com", username: "MMartin", role: ROLE.USER, instances: ["1"], nInstances: 1 },
    { id: "1", name: "Nathan Lee", email: "nathan.lee@example.com", username: "NLee", role: ROLE.USER, instances: ["1"], nInstances: 1 },
    { id: "1", name: "Olivia Harris", email: "olivia.harris@example.com", username: "OHarris", role: ROLE.USER, instances: ["1"], nInstances: 1 },
    { id: "1", name: "Paul Clark", email: "paul.clark@example.com", username: "PClark", role: ROLE.USER, instances: ["1"], nInstances: 1 },
    { id: "1", name: "Quinn Lewis", email: "quinn.lewis@example.com", username: "QLewis", role: ROLE.USER, instances: ["1"], nInstances: 1 },
    { id: "1", name: "Rachel Walker", email: "rachel.walker@example.com", username: "RWalker", role: ROLE.USER, instances: ["1"], nInstances: 1 },
    { id: "1", name: "Steve Hall", email: "steve.hall@example.com", username: "SHall", role: ROLE.USER, instances: ["1"], nInstances: 1 },
    { id: "1", name: "Tina Allen", email: "tina.allen@example.com", username: "TAllen", role: ROLE.USER, instances: ["1"], nInstances: 1 }
]